---
services:
  postgres:
    image: postgres:15
    container_name: db_query_exec
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
